renamedirs = [ "[repo]/src/factorystandard",]
editlines = [ 
[ "[repo]/Makefile", "APPNAME=\"factorystandard\"", "APPNAME=\"[newname]\"",],
[ "[repo]/pyproject.toml", "name = \"factorystandard\"", "name = \"[newname]\"",],
[ "[repo]/pyproject.toml", "packages = [{include = \"factorystandard\", from = \"src\"}]", "packages = [{include = \"[newname]\", from = \"src\"}]",],
]
inherited = [
"LICENSE",
"MANIFEST.in",
".gitignore",
"src/factorystandard/utils.py",
"src/factorystandard/settings.py",
]
